import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
import joblib
import os


def create_lag_features(df: pd.DataFrame, lags: list = [1, 24, 48, 168]) -> pd.DataFrame:
    """
    Create lag features.
    Typical lags:
        1 hour
        24 hours (1 day)
        48 hours (2 days)
        168 hours (1 week)
    """

    for col in df.columns:
        for lag in lags:
            df[f"{col}_lag_{lag}"] = df[col].shift(lag)

    return df


def create_rolling_features(df: pd.DataFrame, windows: list = [24, 72, 168]) -> pd.DataFrame:
    """
    Create rolling window statistical features.
    Typical windows:
        24 hours
        72 hours
        168 hours (1 week)
    """

    for col in df.columns:
        for w in windows:
            df[f"{col}_rollmean_{w}"] = df[col].rolling(window=w).mean()
            df[f"{col}_rollstd_{w}"] = df[col].rolling(window=w).std()

    return df


def scale_features(df: pd.DataFrame, save_path: str = None):
    """
    Scale all numeric features using StandardScaler.
    Save scaler to disk so it can be used later during inference.
    """

    scaler = StandardScaler()
    numeric_df = df.select_dtypes(include=[np.number])
    scaled_values = scaler.fit_transform(numeric_df)
    df[numeric_df.columns] = scaled_values

    if save_path is not None:
        os.makedirs(os.path.dirname(save_path), exist_ok=True)
        joblib.dump(scaler, save_path)

    return df, scaler


def build_feature_set(df: pd.DataFrame, scaler_path: str = "models/scaler.bin"):
    """
    Full feature engineering pipeline:
        1. create lag features
        2. create rolling window features
        3. remove rows with NaN generated by shifting
        4. scale features
    """

    df = create_lag_features(df)
    df = create_rolling_features(df)

    # Remove rows with missing values created by shifting
    df = df.dropna()

    # Scale
    df, scaler = scale_features(df, save_path=scaler_path)

    return df
